assistant_config:
  provider: google
  model: gemini-2.5-pro
  verbose: true
  logprobs: true
  reasoning_effort: null
  max_tokens: 30000
  temperature: 0.8
processing_config:
  detail_level: high
  